# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StockApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StockApp
  pod "Alamofire", "~> 5.4.0"
  pod "SwiftSpinner"
  pod "SwiftyJSON"
end
